export const ROUTES = {
  HOME: "/",
  TOURS: "/tours",
  EXCURSION: "/excursions",
  TOUR_1: "/tours/merzouga-desert-adventure-3-days",
  TOUR_2: "/tours/coast-and-cities-explorer-6-days",
  TOUR_3: "/tours/caravan-and-kasbah-experience-3-days",
  TOUR_4: "/tours/imperial-cities-and-coastline-5-days",
  TOUR_5: "/tours/grand-moroccan-circuit-10-days",
  TOUR_6: "/tours/atlas-and-desert-escape-4-days",
  TOUR_7: "/tours/coastal-and-desert-odyssey-4-days",
  TOUR_8: "/tours/chegaga-wilderness-expedition-3-days",
  TOUR_9: "/tours/northern-heritage-trail-7-days",
  EXCURSION_1: "/excursions/ouzoud-waterfalls-day-trip",
  EXCURSION_2: "/excursions/essaouira-coastal-escape",
  EXCURSION_3: "/excursions/imlil-toubkal-adventure",
  EXCURSION_4: "/excursions/ourika-valley-discovery",
  EXCURSION_5: "/excursions/agafay-desert-sunset",
  EXCURSION_6: "/excursions/sunrise-hot-air-balloon",
  ABOUT: "/about",
  CONTACT: "/contact",
} as const;
